### ISSUE TITLE
The fetching of API should be asynchronous or setTime out for fetch()

### ISSUE THREAD

**Issue by Rajveer07** [devs2gather/devs2gather.github.io#10]
We should use async await for response or use Set Timeout  for the fetch() operation to prevent it from waiting indefinitely for a slow response. This ensures that the application can handle situations where the network response takes too long and should use loading indicator to inform user that the operation is in progress.

**Comment by PradyumnaKrishna** [comment]
No need it is already asynchronous, browsers fetching the file after it loads the page.

<img width="1441" alt="Screenshot 2023-10-06 at 09 11 15" src="https://github.com/devs2gather/devs2gather.github.io/assets/51270439/9163814e-7aa7-4b4f-8b29-ec5ea8197fbd">
