### ISSUE TITLE
I'm interested in incorporating a glitch effect into our open-source page.

### ISSUE THREAD

**Issue by Rajveer07** [devs2gather/devs2gather.github.io#3]
I'm pleased to present a demonstrative 🎥 video showcasing the changes: [Video Link](https://drive.google.com/file/d/1TEyghpYvn88yKCfF-d0TWX-Pya8cXX8D/view?usp=sharing)

I assure you that these modifications won't compromise the page's responsiveness or text formatting.

I appreciate your consideration in this regard.

**Comment by PradyumnaKrishna** [comment]
This looks good, what I am thinking is there a way to set amount of glitch. You can go ahead and create the Pull Request.
