### ISSUE TITLE
Add stats to open source marathon

### ISSUE THREAD

**Issue by PradyumnaKrishna** [devs2gather/devs2gather.github.io#7]
I would like to include stats, regarding the PR (counts, merges), registrations and active participants, successors.

The stats could be like this on the devs2gather web page.
<img width="474" alt="Screenshot 2023-10-02 at 15 56 18" src="https://github.com/devs2gather/devs2gather.github.io/assets/51270439/f4bd1a3f-75ca-452a-84cc-66803ee49ee7">

Current Status
Total PR merged: 77
Merged PRs: 56
Total Registrations: 110+
Active Participants: 30+
Successors: 8

**Comment by Rajveer07** [comment]
will it be on home page ? or on anyother section of webpage

**Comment by PradyumnaKrishna** [comment]
on the marathon page will add it to home page later.

**Comment by PradyumnaKrishna** [comment]
Closed with #9
